### ISSUE TITLE
How do disable particular date?

### ISSUE THREAD

**Issue by bilsamtech** [crazychicken/t-datepicker#4]
How do I disable a particular date? Let's say someone booked future dates and now I'm having look on the calendar.

**Comment by crazychicken** [comment]
Thank you for your feeback!

That is a good idea, i will update it in the next version.
If you can't wait for the next version, i suggest using: [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#datesdisabled).

**Comment by luntik4344** [comment]
> Thank you for your feeback!
> 
> That is a good idea, i will update it in the next version.
> If you can't wait for the next version, i suggest using: [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#datesdisabled).

And how long nearly to wait for a new version?:)
I have made a function to disable particular dates myself (based on fnDataEvent), but the problem is that I don't know how to check disabled days while the user chooses the range.
So I need to deny the user to choose the range of dates which contains disabled dates.

**Comment by crazychicken** [comment]
Hi @luntik4344,
I have just updated version 1.0.3. You can use option **[dateDisabled](https://t-datepicker.getqwerty.com/options.html#dateDisabled)**

Thank you.
