### ISSUE TITLE
Same check-in and check-out date

### ISSUE THREAD

**Issue by Datesta** [crazychicken/t-datepicker#6]
Hi there,

First of all, really nice plugin! 
I'm wondering if it is possible to use this when having the same check-in and check-out date. I want to use it for rentals, but these can be for a single day so logically i want it so the user would click only one day if they want to rent for one day only. I have tried to rewrite the script a bit to accomodate this functionality but i cannot see what will break based on this change.

**Comment by Hungtran2140** [comment]
Did you complete this task? I am trying to do that but not success

**Comment by youwwwmaster** [comment]
I have the same problem and I don't understand how to solve it? How did you do it?

**Comment by Finnu** [comment]
Hey, if anyone is still looking (or will) for the solution to allow same dates in check-in and check-out using t-datepicker. Here is one. 

**What you need to do?**
You need to use the built-in events for that, with some timeouts in order to get access to the HTML elements that holds the data or the ones you plan to assign data to, since these are generated. 

**The code**
You can get it from this gist:

https://gist.github.com/Finnu/b337105c27c4629e8bdd01150c2c4edc

Sry for my english just in case :3
